services:
  db:
    image: postgres:16
    container_name: o2t4_db
    env_file: # Файл с переменными окружения (Вместо environment)
      - .env
    ports:
      - 5433:5432
    volumes:
      - o2t4_postgresdata:/var/lib/postgresql/data
    networks:
      - o2t4_network
    restart: always

  app:
    image: appimg
    build:
      context: .
    container_name: ytr_app
    # volumes:
    #   - ./pages:/code/pages
    env_file:
      - .env-docker
    depends_on: # Запускаем только после запуска БД и Redis (depends on = зависит от)
      - db
    command: sh -c "uvicorn app.fastapi_app:app --port 5000 --host 0.0.0.0 --proxy-headers"
    ports:
      - 5001:5000
    networks:
      - o2t4_network

volumes:
  o2t4_postgresdata:
    name: backend_o2t4_postgresdata

networks:
  o2t4_network:
    driver: bridge
