-- Additive only: create channel_rating next to existing channel_stat.
-- Does NOT drop pv_* from channel_stat.
-- Past periods: COPY from channel_stat ⋈ channel (no rebuild).
--
-- Naming: channel_* = YT channel counters; video_*/views_*/new_* = from videos;
-- *_mom = month-over-month change. API will use the same names (breaking).
--
-- Apply once:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrate_channel_rating.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public.channel_rating (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id character varying NOT NULL REFERENCES public.channel(channel_id),
    report_period date NOT NULL,

    -- snapshotted channel dims
    channel_title text,
    description text,
    custom_url text,
    thumbnail_url text,
    category_id integer,

    -- when YT channel statistics were fetched (NOT row created_at)
    stats_at timestamp without time zone,

    -- YT channel counters (cumulative at stats_at)
    channel_views bigint,
    channel_subscribers bigint,
    channel_videos integer,

    -- MoM of those counters (from prev channel_stat)
    channel_views_mom bigint,
    channel_subscribers_mom bigint,
    channel_videos_mom integer,

    -- from video_stat aggregates
    new_longs integer,
    new_shorts integer,
    duration_sec bigint,
    video_views bigint,
    views_new_long bigint,
    views_new_short bigint,
    views_old_long bigint,
    views_old_short bigint,
    video_likes bigint,
    video_comments bigint,

    score bigint,
    score_mom bigint,
    rank integer,
    rank_mom integer,

    -- future per-channel annotations, e.g. {"clickbait_heavy": true}
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,

    _created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_channel_rating UNIQUE (channel_id, report_period)
);

CREATE INDEX IF NOT EXISTS idx_channel_rating_report_period
    ON public.channel_rating (report_period);
CREATE INDEX IF NOT EXISTS idx_channel_rating_cat_period_rank
    ON public.channel_rating (category_id, report_period, rank);

-- Seed all historical periods from existing channel_stat denorm + channel dims
INSERT INTO public.channel_rating (
    channel_id, report_period,
    channel_title, description, custom_url, thumbnail_url, category_id,
    stats_at, channel_views, channel_subscribers, channel_videos,
    channel_views_mom, channel_subscribers_mom, channel_videos_mom,
    new_longs, new_shorts, duration_sec,
    video_views, views_new_long, views_new_short, views_old_long, views_old_short,
    video_likes, video_comments,
    score, score_mom, rank, rank_mom,
    meta, _created_at, _updated_at
)
SELECT
    cs.channel_id,
    cs.report_period,
    ch.channel_title,
    ch.description,
    ch.custom_url,
    ch.thumbnail_url,
    ch.category_id,
    cs.data_at,
    cs.channel_view_count,
    cs.subscriber_count,
    cs.video_count,
    cs.pc_view,
    cs.pc_subscriber,
    cs.pc_video,
    cs.pv_video_long,
    cs.pv_video_short,
    cs.pv_duration,
    cs.pv_view,
    cs.pv_view_new_long,
    cs.pv_view_new_short,
    cs.pv_view_old_long,
    cs.pv_view_old_short,
    cs.pv_like,
    cs.pv_comment,
    cs.pv_score,
    cs.pv_score_change,
    cs.pv_score_rank,
    cs.pv_score_rank_change,
    '{}'::jsonb,
    COALESCE(cs.updated_at, CURRENT_TIMESTAMP),
    COALESCE(cs.updated_at, CURRENT_TIMESTAMP)
FROM public.channel_stat AS cs
JOIN public.channel AS ch ON ch.channel_id = cs.channel_id
WHERE cs.report_period IS NOT NULL
ON CONFLICT (channel_id, report_period) DO NOTHING;

CREATE OR REPLACE FUNCTION public.channel_rating_set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW._updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_channel_rating_set_updated_at ON public.channel_rating;
CREATE TRIGGER trg_channel_rating_set_updated_at
    BEFORE UPDATE ON public.channel_rating
    FOR EACH ROW
    EXECUTE FUNCTION public.channel_rating_set_updated_at();

COMMIT;

-- Sanity (optional):
-- SELECT count(*) FROM channel_stat WHERE report_period IS NOT NULL;
-- SELECT count(*) FROM channel_rating;
-- SELECT report_period, count(*) FROM channel_rating GROUP BY 1 ORDER BY 1 DESC LIMIT 12;
